### ISSUE TITLE
Missing archidefs.pkl file? 

### ISSUE THREAD

**Issue by YorkLouis** [KingLear194/BlackLittermanEnd2End#1]
Seems to be missing archidefs.pkl file? Can you provide me some suggestions?

**Comment by KingLear194** [comment]
archidefs.pkl is not part of the source code, but rather is an input file that contains the definitions of the neural networks that are used to produce views, as well as other parameters of the Black-Litterman pipeline we use. It is produced in the file src/etf_preprocessing.py according to other inputs of the user.
