### ISSUE TITLE
Missing "config_file.json"

### ISSUE THREAD

**Issue by eduardomsjr** [KingLear194/BlackLittermanEnd2End#2]
When I try to run the script src/SlurmScripts/slurm_etf_training.sh, the error "FileNotFoundError: [Errno 2] No such file or directory:" is shown in the config_file.json file reference. Could you provide the file or show its format? Thanks in advance.

**Comment by KingLear194** [comment]
One needs to run the etf_preprocessing.py file first, or a version similar to that depending on your data and NN models. etf_preprocessing.py prepares the inputs for the training and inference done in slurm_etf_training.sh and the python scripts the latter calls. Among the side effects of production in etf_preprocessing is also the production of the file config_file.json -- see lines 265-266 (and preceding lines of code) in etf_preprocessing.py
